{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(pizza_purchases_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(pizza_purchases_failure_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_purchase_revenue_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(pizza_purchase_latency_ms_milliseconds_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP requests by method/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_requests_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "{{method}}{{metric_type}}"
    }
   ]
  },
  {
   "title": "Authentication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(auth_success_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "{{method}} Success"
    },
    {
     "expr": "rate(auth_failure_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "{{method}} Failure"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_request_latency_ms_milliseconds_total{source=\"jwt-pizza-service\"}[1m]) / rate(http_request_count_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU and memory usage percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "system_memory_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  }
 ]
}